version: "3.9"

services:
  # -------------------------
  # Spring API
  # -------------------------
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    environment:
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    restart: always

  # -------------------------
  # Angular UI
  # -------------------------
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui
    depends_on:
      - api
    ports:
      - "4200:80" # Nginx serves Angular on port 80 inside container
    restart: always